name: Daily Random Commits

on:
  schedule:
    - cron: '15 4 * * *'  # Runs every day at 04:15 UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Generate Random Commits (5–10)
        run: |
          git config user.name "Reshav Sharma"
          git config user.email "23f2005430@ds.study.iitm.ac.in"
          
          count=$(( RANDOM % 6 + 5 ))  # Random number between 5 and 10
          echo "Generating $count commits"

          for i in $(seq 1 $count); do
            echo "Commit $i at $(date -u)" >> daily-commit-log.txt
            git add daily-commit-log.txt
            git commit -m "Auto commit $i at $(date -u)"
            sleep 1  # Small delay to ensure unique timestamps
          done

      - name: Push Commits
        run: |
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}.git
